### PR TITLE
Add mangoapp

### LINKED ISSUE #12: Support for mangoapp
Does this flatpak support mangoapp?
If not, can the support be added in this Flatpak? 
Mangoapp is a HUD for gamescope, released with MangoHUD, with more Gamescope specific features

### PR DESCRIPTION
**Pull request by TheEvilSkeleton**
I haven't tested yet.

Closes #12.

### CODE REVIEW

**Comment by TheEvilSkeleton** [comment]
> ```
> imgui| Run-time dependency glew found: NO (tried pkgconfig and cmake)
> ../subprojects/imgui-1.81/meson.build:38:0: ERROR: Dependency "glew" not found, tried pkgconfig and cmake
> A full log can be found at /run/build/MangoHud/_flatpak_build/meson-logs/meson-log.txt
> FB: host_command_exited_cb 1429945 256
> ]2;flatpak-builder: Cleanup MangoHudError: module MangoHud: Child process exited with code 1
> FB: Unmounting read-only fs: fusermount -uz /srv/buildbot/worker/build-x86_64-7/build/.flatpak-builder/rofiles/rofiles-09PZCM
> dbus-daemon[1428956]: Reloaded configuration
> ```

I'm not sure how...

**Comment by gasinvein** [comment]
I guess you need to add `prepend-pkg-config-path: /usr/lib/extensions/vulkan/MangoHud/lib/x86_64-linux-gnu/pkgconfig`.
And build GLEW manually, since we need it for both arches (assuming mangoapp is multilib, too).

**Comment by gasinvein** [comment]
So, I've rebased it on `beta` and changed base branch to `beta`, since latest MangoHud requires meson 0.60 only available in SDK `22.08beta`, and I don't want to mess with backporting it, since `22.08` will be released soon.
Also added a plenty of build-time dependencies.
I still have no idea how to use it, so please test.

**Comment by TheEvilSkeleton** [comment]
Unfortunately there's no way for me to test it using Bottles, as I am unable to run Bottles with the newer runtimes. We should delay this until new runtimes are released.

**Comment by TheEvilSkeleton** [comment]
bot, build

**Comment by gasinvein** [comment]
So, did anyone test this PR and can confirm it works?
I've never used mangoapp and have no idea of what it is or what it does.

**Comment by TheEvilSkeleton** [comment]
mangoapp is designed to run inside Gamescope.

https://github.com/flightlessmango/MangoHud/blob/05133ae3cd05285c4cf373896dd0ce2a6e4e4169/data/mangoapp.1#L13-L17

**Comment by TheEvilSkeleton** [comment]
bot, build

**Comment by TheEvilSkeleton** [comment]
I can confirm it works for me with this MR https://github.com/bottlesdevs/Bottles/pull/2108.

**Comment by TheEvilSkeleton** [comment]
This can be merged.

**Comment by gasinvein** [comment]
I'll take your word on it (and CC you if someone reports a mangoapp-related issue).

**Pull request merged**
