### PR TITLE
Add patch setting cpu_family within vulkay layer name

### LINKED ISSUE #32: Don't work after steam update to org.freedesktop.Platform 23.08.0
I have org.freedesktop.Platform.VulkanLayer.MangoHud 23.08 but it doent work.

### PR DESCRIPTION
**Pull request by ghost**
Thanks to [TrixieUA](https://github.com/TrixieUA) per https://github.com/flathub/org.freedesktop.Platform.VulkanLayer.MangoHud/issues/32 See also: https://github.com/flightlessmango/MangoHud/commit/5754ca13ee2cdf19a76b4fc79dd914a58d6371f5

This patch restores overlay for both `com.valvesoftware.Steam.CompatibilityTool.Proton` Flatpak builds of Proton and non-Flatpak builds on my systems.

Fixes #32

### CODE REVIEW

**Comment by okseb** [comment]
Can confirm this also restores functionality on my system :+1: LGTM

**Comment by cassiofb-dev** [comment]
My steam installed MangoHud in the branch 22.08, will it be merged in that branch to or there is a way to changed the branch?

**Comment by gasinvein** [comment]
Does anyone know if they're planning to do a new release soon, given the current one is known-broken?

**Comment by ghost** [comment]
> My steam installed MangoHud in the branch 22.08, will it be merged in that branch to or there is a way to changed the branch?

This pull request only encompasses the 23.08 branch where there is a known problem. My understanding is that the 22.08 builds use an earlier release of the vulkan library which don't exhibit the problem intended to be resolved.

> Does anyone know if they're planning to do a new release soon, given the current one is known-broken?

I've no idea but it looks like significant activity has occurred over the past few days/months (including newly added features)  so perhaps it's possible.

**Comment by TrixieUA** [comment]
> Does anyone know if they're planning to do a new release soon, given the current one is known-broken?

I don't think there will be any releases soon.
And its just 2 lines patch so it's better to include it and have working mangohud rather than wait for a new release for idk how long.

**Comment by gasinvein** [comment]
Ok, let's merge it. Thanks.

**Comment by ghost** [comment]
Thank you very much!

**Pull request merged**
