### PR TITLE
Update to 0.7.0

### PR DESCRIPTION
**Pull request by chardinson**
New release: https://github.com/flightlessmango/MangoHud/releases/tag/v0.7.0

### CODE REVIEW

**Comment by jntesteves** [comment]
@chardinson I believe the build failure is because you also have to revert commit 4b58efd21b7108972b4e7904ccf0683c294541bf introduced in #33. That patch shouldn't be needed anymore because it's already in the upstream repository.

**Comment by tim77** [comment]
We need to add few python deps here i believe which required by `mangoplot` introduced in this new version.

**Comment by chardinson** [comment]
These new Python `numpy` and `matplotlib` dependencies are added directly to the manifest or in a separate file as `python3-mako.json`

cc @gasinvein

**Comment by gasinvein** [comment]
I presume this new `mangoplot` program is supplementary? Should we land this update without it and sort out the python dependencies later?

**Comment by tim77** [comment]
> I presume this new `mangoplot` program is supplementary? Should we land this update without it and sort out the python dependencies later?

Probably. I would suggest also drop [this](https://github.com/flightlessmango/MangoHud/commit/dc1761e98a435aaee6a919e21f43b85cc38500ac) and build with system lib.

**Comment by gasinvein** [comment]
> > I presume this new `mangoplot` program is supplementary? Should we land this update without it and sort out the python dependencies later?
> 
> Probably. 

Ok, if anyone needs this program, let's let them file an issue.

>I would suggest also drop [this](https://github.com/flightlessmango/MangoHud/commit/dc1761e98a435aaee6a919e21f43b85cc38500ac) and build with system lib.

Statically linking with libstdc++ is pointless in Flatpak (as in any properly packaged build), but should be harmless here.

@chardinson Thanks!

**Comment by Perkolator** [comment]
Should this be available in Flathub now? "flatpak update" can't find anything for me.

**Comment by Mershl** [comment]
> Should this be available in Flathub now? "flatpak update" can't find anything for me.

Update is available on Flathub. Keep in mind that this is for the 23.08 branch. You might still use the 22.08 branch.

**Comment by Perkolator** [comment]
> Update is available on Flathub. Keep in mind that this is for the 23.08 branch. You might still use the 22.08 branch.

Thanks. One has to manually uninstall branch 22.08 and then reinstall as 23.08. I wish flatpak would fix this system. Unfortunately the 23.08 branch doesn't work with Bottles. :( Flatpak stuff needs to mature a bit, this is just too cumbersome, especially the branch system that doesn't inform/offer updates (for a reason it seems?). This is just not that user friendly, especially not noobie friendly. Sorry for ranting, I was waiting several new features from this version.

**Comment by Mershl** [comment]
> One has to manually uninstall branch 22.08 and then reinstall as 23.08.

> Unfortunately the 23.08 branch doesn't work with Bottles.

Both branches can co-exist on your system. 22.08 apps will use 22.08 runtime extensions and 23.08 their respective 23.08 runtime dependencies.

That being said. I completly agree with you. Steam has already updated to 23.08 which brought up this situation again as games where users specified mangohud in their launch parameters would crash until a user manually installed mangohud 23.08. Lutris and Bottles are still on 22.08 which will use mangohud 22.08 (which is still v0.6.9 - and probably will end there).

Thinking out loud: There needs to be a detection in `flatpak update` that realizes a loose dependency of say `com.valvesoftware.Steam` and `org.freedesktop.Platform.VulkanLayer.MangoHud`. Difficult part is that these dependencies are not explicit, this might bring up other challenges.

**Pull request merged**
